# Generated by Django 6.0.5 on 2026-07-26 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PERSONA', 'Persona natural'), ('EMPRESA', 'Empresa')], default='PERSONA', max_length=10)),
                ('nombre', models.CharField(max_length=150)),
                ('identificacion', models.CharField(help_text='Cédula o RUC', max_length=20, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('unidad_medida', models.CharField(choices=[('KG', 'Kilogramos'), ('G', 'Gramos'), ('L', 'Litros'), ('ML', 'Mililitros'), ('UND', 'Unidades')], max_length=5)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_por_persona', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('tiempo_menu', models.CharField(choices=[('ENTRADA', 'Entrada'), ('PRINCIPAL', 'Plato principal'), ('ACOMPANAMIENTO', 'Acompañamiento'), ('POSTRE', 'Postre'), ('BEBIDA', 'Bebida'), ('OTRO', 'Otro')], max_length=20)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tiempo_preparacion', models.PositiveIntegerField(default=15, help_text='Tiempo aproximado en minutos')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='platos/')),
                ('tecla_rapida', models.PositiveSmallIntegerField(blank=True, help_text='Número utilizado por Hotkeys-js', null=True, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['tiempo_menu', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Utileria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('MESA', 'Mesas'), ('SILLA', 'Sillas'), ('VAJILLA', 'Vajilla'), ('CUBIERTOS', 'Cubiertos'), ('MANTELERIA', 'Mantelería'), ('DECORACION', 'Decoración'), ('EQUIPO', 'Equipo de cocina'), ('OTRO', 'Otro')], max_length=20)),
                ('cantidad_total', models.PositiveIntegerField(default=0)),
                ('costo_reposicion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cocinero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150)),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('especialidad', models.CharField(blank=True, max_length=120)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_cocinero', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventoCatering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_evento', models.CharField(max_length=180)),
                ('tipo_servicio', models.CharField(choices=[('BODA', 'Boda'), ('CUMPLEANOS', 'Cumpleaños'), ('EMPRESARIAL', 'Evento empresarial'), ('GRADUACION', 'Graduación'), ('SOCIAL', 'Evento social'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('direccion', models.CharField(max_length=255)),
                ('numero_personas', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('COTIZADO', 'Cotizado'), ('CONFIRMADO', 'Confirmado'), ('PREPARACION', 'En preparación'), ('EN_CURSO', 'En curso'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='COTIZADO', max_length=20)),
                ('total_contratado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('anticipo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='pedidos.cliente')),
            ],
            options={
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateTimeField()),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('direccion_entrega', models.CharField(max_length=255)),
                ('vehiculo', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PREPARANDO', 'Preparando carga'), ('EN_RUTA', 'En ruta'), ('ENTREGADA', 'Entregada'), ('INCIDENCIA', 'Con incidencia'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_asignadas', to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='pedidos.eventocatering')),
            ],
            options={
                'ordering': ['fecha_salida'],
            },
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True)),
                ('numero_mesa', models.PositiveIntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PREPARANDO', 'Preparando'), ('LISTA', 'Lista'), ('DESPACHADA', 'Despachada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_despacho', models.DateTimeField(blank=True, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comandas', to='pedidos.eventocatering')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='EventoCocinero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('JEFE', 'Chef principal'), ('COCINERO', 'Cocinero'), ('AYUDANTE', 'Ayudante de cocina'), ('PASTELERO', 'Pastelero')], default='COCINERO', max_length=20)),
                ('horas_asignadas', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cocinero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='pedidos.cocinero')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_cocineros', to='pedidos.eventocatering')),
            ],
        ),
        migrations.AddField(
            model_name='eventocatering',
            name='cocineros',
            field=models.ManyToManyField(related_name='eventos', through='pedidos.EventoCocinero', to='pedidos.cocinero'),
        ),
        migrations.AddField(
            model_name='eventocatering',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='pedidos.menu'),
        ),
        migrations.CreateModel(
            name='MenuPlato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_menu', models.CharField(choices=[('ENTRADA', 'Entrada'), ('PRINCIPAL', 'Plato principal'), ('ACOMPANAMIENTO', 'Acompañamiento'), ('POSTRE', 'Postre'), ('BEBIDA', 'Bebida'), ('OTRO', 'Otro')], max_length=20)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('cantidad_por_persona', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_menu', to='pedidos.menu')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_menu', to='pedidos.plato')),
            ],
            options={
                'ordering': ['tiempo_menu', 'orden'],
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='platos',
            field=models.ManyToManyField(related_name='menus', through='pedidos.MenuPlato', to='pedidos.plato'),
        ),
        migrations.CreateModel(
            name='DetalleComanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos.comanda')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_comanda', to='pedidos.plato')),
            ],
        ),
        migrations.CreateModel(
            name='RecetaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, help_text='Cantidad necesaria para una porción', max_digits=10)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recetas', to='pedidos.insumo')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes_receta', to='pedidos.plato')),
            ],
        ),
        migrations.CreateModel(
            name='EventoUtileria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('RESERVADA', 'Reservada'), ('DESPACHADA', 'Despachada'), ('DEVUELTA', 'Devuelta'), ('DANADA', 'Dañada'), ('PERDIDA', 'Perdida')], default='RESERVADA', max_length=20)),
                ('cantidad_devuelta', models.PositiveIntegerField(default=0)),
                ('observaciones', models.TextField(blank=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utileria_asignada', to='pedidos.eventocatering')),
                ('utileria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='pedidos.utileria')),
            ],
        ),
        migrations.AddConstraint(
            model_name='eventococinero',
            constraint=models.UniqueConstraint(fields=('evento', 'cocinero'), name='cocinero_unico_por_evento'),
        ),
        migrations.AddConstraint(
            model_name='menuplato',
            constraint=models.UniqueConstraint(fields=('menu', 'plato'), name='plato_unico_por_menu'),
        ),
        migrations.AddConstraint(
            model_name='recetadetalle',
            constraint=models.UniqueConstraint(fields=('plato', 'insumo'), name='ingrediente_unico_por_plato'),
        ),
        migrations.AddConstraint(
            model_name='eventoutileria',
            constraint=models.UniqueConstraint(fields=('evento', 'utileria'), name='utileria_unica_por_evento'),
        ),
    ]
